version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: rc-car-app-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - 3306

  api:
    build: ./api
    container_name: rc-car-app-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://rc-car-app-mysql:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    expose:
      - 8080
    privileged: true
#    volumes:
#      - /var/run/dbus/:/var/run/dbus/:z
    network_mode: "host"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: rc-car-app-mysql
    depends_on:
      - db
    expose:
      - 80

volumes:
  mysql-data: